models/Retails.php
<?php

namespace app\models;
use app\traits\AuditTrailsTrait;
use Yii;

/**
 * This is the model class for table "retails".
 *
 * @property int $retails_id
 * @property string $description
 * @property int $created_at
 * @property int $created_by
 * @property int $updated_at
 * @property int $updated_by
 * @property int $customer
 *
 * @property Customer $customer0
 * @property RetailsInfo[] $retailsInfos
 */
class Retails extends \yii\db\ActiveRecord
{
    use AuditTrailsTrait;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'retails';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['customer'], 'required'],
            [['created_at', 'created_by', 'updated_at', 'updated_by', 'customer'], 'integer'],
            [['description'], 'string', 'max' => 2000],
            [['customer'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer' => 'phone']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'retails_id' => Yii::t('app', 'Retails ID'),
            'description' => Yii::t('app', 'Description'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'customer' => Yii::t('app', 'Customer'),
        ];
    }

    /**
     * Gets query for [[Customer0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer0()
    {
        return $this->hasOne(Customer::className(), ['phone' => 'customer']);
    }

    /**
     * Gets query for [[RetailsInfos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRetailsInfos()
    {
        return $this->hasMany(RetailsInfo::className(), ['retails_id' => 'retails_id']);
    }
}

controllers/RetailsController.php
<?php

namespace app\controllers;

use app\models\Retails;
use app\models\RetailsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\InStockSearch;
use app\models\SparePartsSearch;;
use app\models\RetailsInfoSearch;
use yii\data\SqlDataProvider;
use app\models\CustomerRetailsSearch;
//use app\models\Pdfprint;

/**
 * RetailsController implements the CRUD actions for Retails model.
 */
class RetailsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Retails models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new RetailsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Retails model.
     * @param int $retails_id Retails ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($retails_id)
    {
        \yii\helpers\Url::remember();

        //$searchModel2= new CustomerRetailsSearch();
        // $RetaildataProvider= $searchModel2->search($this->request->queryParams);
        // $RetaildataProvider->query->andWhere(['retails_id'=>$retails_id]);

        $searchModel = new RetailsInfoSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        $dataProvider->query->andWhere(['retails_id'=>$retails_id]);

        //$this->renderPartial('/retails-info/index');
        return $this->render('view', [
            'model' => $this->findModel($retails_id),
            'dataProvider'=>$dataProvider,
            'searchModel'=>$searchModel,
        ]);
    }

    /**
     * Creates a new Retails model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Retails();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['stock', 'retails_id' => $model->retails_id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionStock($retails_id)
    {

        \yii\helpers\Url::remember();

        $searchModel = new SparePartsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        $model=new RetailsInfoSearch();
        $model->retails_id=$retails_id;

        $customer=Retails::find()->where(['retails_id'=>$retails_id])->one()->customer;
        

        //$searchCustomer = new Customer();
        $sql="SELECT * FROM customer WHERE phone=$customer";
        $count = \Yii::$app->db->createCommand("SELECT COUNT(*) FROM ($sql) t")->queryScalar();

        $CustomerdataProvider = new SqlDataProvider([
            'sql' => $sql,
            'totalCount' => $count,
            //'params' => $params,
            'pagination' => [
                'pageSize' => false,
            ],
        ]);

        $searchModel2= new CustomerRetailsSearch();
        $RetaildataProvider= $searchModel2->search($this->request->queryParams);
        $RetaildataProvider->query->andWhere(['retails_id'=>$retails_id]);
        return $this->render('stock', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'CustomerdataProvider' => $CustomerdataProvider,
            'RetaildataProvider'=>$RetaildataProvider,
            //'searchModel2'=>$searchModel2,

        ]);
    }


    public function actionInvoice($retails_id)
    {

        $this->layout = 'login';
        \yii\helpers\Url::remember();

        // $searchModel = new InStockSearch();
        // $dataProvider = $searchModel->search($this->request->queryParams);

        // $model=new RetailsInfoSearch();
        // $model->retails_id=$retails_id;


        // $searchModel2= new CustomerRetailsSearch();
        // $RetaildataProvider= $searchModel2->search($this->request->queryParams);
        // $RetaildataProvider->query->andWhere(['retails_id'=>$retails_id]);
        return $this->render('invoice1', [
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
            // 'CustomerdataProvider' => $CustomerdataProvider,
           // 'RetaildataProvider'=>$RetaildataProvider,
            //'searchModel2'=>$searchModel2,

        ]);
    }
    public function actionReceipt($retails_id)
    {

        \yii\helpers\Url::remember();

        // $searchModel = new InStockSearch();
        // $dataProvider = $searchModel->search($this->request->queryParams);

        $model=new RetailsInfoSearch();
        $model->retails_id=$retails_id;

        $customer=Retails::find()->where(['retails_id'=>$retails_id])->one()->customer;
        

        //$searchCustomer = new Customer();
        // $sql="SELECT * FROM customer WHERE phone=$customer";
        // $count = \Yii::$app->db->createCommand("SELECT COUNT(*) FROM ($sql) t")->queryScalar();

        // $CustomerdataProvider = new SqlDataProvider([
        //     'sql' => $sql,
        //     'totalCount' => $count,
        //     //'params' => $params,
        //     'pagination' => [
        //         'pageSize' => false,
        //     ],
        // ]);

        // $rsql="SELECT * FROM retails_info WHERE retails_id=$retails_id";
        // $rcount = \Yii::$app->db->createCommand("SELECT COUNT(*) FROM ($rsql) t")->queryScalar();

        // $RetaildataProvider = new SqlDataProvider([
        //     'sql' => $rsql,
        //     'totalCount' => $rcount,
        //     //'params' => $params,
        //     'pagination' => [
        //         'pageSize' => false,
        //     ],
        // ]);

        $searchModel2= new CustomerRetailsSearch();
        $RetaildataProvider= $searchModel2->search($this->request->queryParams);
        $RetaildataProvider->query->andWhere(['retails_id'=>$retails_id]);
        return $this->render('receipt', [
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
            // 'CustomerdataProvider' => $CustomerdataProvider,
            'RetaildataProvider'=>$RetaildataProvider,
            //'searchModel2'=>$searchModel2,

        ]);
    }

    /**
     * Updates an existing Retails model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $retails_id Retails ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($retails_id)
    {
        $model = $this->findModel($retails_id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['stock', 'retails_id' => $model->retails_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Retails model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $retails_id Retails ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($retails_id)
    {
        $this->findModel($retails_id)->delete();

        return $this->redirect(['index']);
        
    }

    /**
     * Finds the Retails model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $retails_id Retails ID
     * @return Retails the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($retails_id)
    {
        if (($model = Retails::findOne(['retails_id' => $retails_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(\Yii::t('app', 'The requested page does not exist.'));
    }
}

views/retails/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Customer;
use kartik\select2\Select2;


/* @var $this yii\web\View */
/* @var $model app\models\Retails */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="retails-form">

    <?php $form = ActiveForm::begin(); ?>

    <!-- <?= $form->field($model, 'customer')->textInput() ?> -->

<?= $form->field($model, 'customer')->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(Customer::find()->all(), 'phone', function ($model) {
                        return $model->name;
                    }),
                    'options' => ['placeholder' => Yii::t('app', 'Select Customer')],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ])  ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

   
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/retails/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RetailsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="retails-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'retails_id') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'customer') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/retails/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Retails */

$this->title = Yii::t('app', 'Create Retails');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Retails'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="retails-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/retails/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Retails');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="retails-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Retails'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'retails_id',
            'description',
            // 'created_at',
            // 'created_by',
            // 'updated_at',
            //'updated_by',
            'customer',
            // [
            //     'class' => ActionColumn::className(),
            //     'urlCreator' => function ($action, app\models\Retails $model, $key, $index, $column) {
            //         return Url::toRoute([$action, 'retails_id' => $model->retails_id]);
            //      }
            // ],
            [
                'class' => ActionColumn::className(),
            
                'template' => '{view}',  // the default buttons + your custom button
            'urlCreator' => function ($action, app\models\Retails $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'retails_id' => $model->retails_id]);
                 }
            
        ],
        ],
    ]); ?>


</div>

views/retails/invoice1.php
<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript">
//  window.onload = function() { window.print(); }
window.onload = function() { window.print();
    
 // window.onafterprint(history.back());
  // window.afterclick(history.back());
}

</script>

    <meta charset="UTF-8">
    <title>DotNetTec - Invoice html template bootstrap</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.css'>
</head>

<body>


<?php
$conn=new mysqli("localhost","root","","stock");
if($conn->connect_error){
    die("connection failed : ".$conn->connect_error);
}

$id=$_REQUEST['retails_id'];
$sql="select spare_part,quantity,price,discount,(quantity*price) as total from retails_info where retails_id=$id";

$statment="select sum((quantity*price)-((quantity*price*discount)/100)) as TOT from retails_info where retails_id=$id";

$tot=$conn->query($statment);

$cust="select c.phone, c.name, c.address from customer c, retails r where r.customer=c.phone and retails_id=3";
$customer=$conn->query($cust);

$result=$conn->query($sql);
?>

    <div class="container">
        <div class="card">
            <div class="card-h" style="text-align: center;" >
                <strong>[COMPANY NAME]</strong><br> 
                <strong>[COMPANY ADDRESS]</strong><br>
                <strong>[PHONE NUMBER]</strong><br>
                <strong>[FAX NUMBER]</strong> <br>
                <strong>[EMAIL ADDRESS]</strong><br>
                <strong>PRICE QUOTATION</strong>

            </div><br><br>
            <div class="card-header" style="background-color: rgb(80, 97, 150);">
                <strong>Customer Information</strong>
                <!-- <span class="float-right"> <strong>Status:</strong> Pending</span> -->
               
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <!-- <div>
                            <strong>DotNetTec</strong>
                        </div> -->
                        <?php   $ro = mysqli_fetch_array($customer); ?>

                        <div><strong>Name: </strong><?php echo $ro['name'];?></div>
                        <div><strong>Address: </strong><?php echo $ro['address'];?></div>
                        <div><strong>Zip/Postal Code: </strong></div>
                        <div><strong>Phone Number: </strong> <?php echo "0".$ro['phone']; ?></div>
                    </div>
                    
                    <div class="col-sm-6">
                        <!-- <h6 class="mb-3">To:</h6>
                        <div>
                            <strong>Robert Maxwel</strong>
                        </div> -->
                        <div><strong>Date: </strong><?php echo date('Y-m-d') ?></div>
                        <div><strong>Quote No: </strong></div>

                    </div>
                </div>

                <div class="table-responsive-sm">
                    <table class="table table-bordered">
                        <thead>
                            <tr style="background-color: rgb(80, 97, 150);">
                                <th class="center">Item Name</th>
                                <th class="right">Unit Cost</th>
                                <th class="center">Qty</th>
                                <th class="center">Discount</th>
                                <th class="right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                          <?php  
                          
                          if($result->num_rows > 0){
                                while($row = $result->fetch_array()){
                                  echo "<tr><td>".$row["spare_part"]."</td><td>".$row["price"]."</td><td>".$row["quantity"]."</td><td>".$row["discount"]."</td><td>".$row["total"]."</td></tr>";
                                }
                            }      
                             
                            ?>
       
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-5">

                    </div>

                    <div class="col-lg-4 col-sm-5 ml-auto">
                        <table class="table table-clear">
                            <tbody>
                                <tr>
                                    <td class="left">
                                        <strong>Subtotal</strong>
                                    </td>
                                    <td class="right">
                                        
                                   <?php
                                   while ($r = mysqli_fetch_array($tot)) {
                                    echo $r['TOT'];
                                
                                    //echo $row["TOT"];
                                ?></td>
                                </tr>
                                <tr>
                                    <td class="left">
                                        <strong>Discount (20%)</strong>
                                    </td>
                                    <td class="right"> <?php
                                    //  echo $row["discount"];
                              ?></td>
                                </tr>

                                <tr>
                                    <td class="left">
                                        <strong>Total amount</strong>
                                    </td>
                                    <td class="right">
                                        <strong> <?php
                                         
                                            echo $r['TOT'];
                                        }
                                    //echo $row["TOT"];
                                 ?></strong>
                                    </td>
                                </tr>

                           </tbody>

                        </table>
                     <?php 
                    $conn->close();
                     ?>
                    </div>
                    
                    <p><strong>Note:</strong> the customer shall be billed out upon acceptance of this price quotation.Payment due to the prior to the delivery of items</p><br><br><br>
                   <footer style="font-size: smaller;">For further inquiries please contact [COMPANY CONTACT NUMBER] or email us at [E-MAIL ADDRESS]</footer>
                </div>
            </div>
          
        </div>
    </div>
</body>
</html>

views/retails/stock.php
<?php

use app\models\Customer;
use app\models\Retails;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use kartik\grid\GridView;

//use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Retails');
$this->params['breadcrumbs'][] = $this->title;


?>

<?= \dixonstarter\pdfprint\Pdfprint::widget();?>
<?= \dixonstarter\pdfprint\Pdfprint::widget([
  'elementClass' => '.btn-pdfprint'
]);?>

<a href="receipt.pdf" class="btn-pdfprint">open</a>

<div class="retails-stock">

    <h1><?= Html::encode($this->title) ?></h1>

    <!-- <p>
        <?= Html::a(Yii::t('app', 'Create Retails'), ['customer'], ['class' => 'btn btn-success']) ?>
    </p> -->

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


    <?= GridView::widget([
        'dataProvider' => $CustomerdataProvider,
       
       // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'phone',
            //'customer',
            'name',
            'address',
            
        ],
    ]); ?>
<script type="text/javascript">

    function printlayer(Layer)
    {
        var generator=window.open("invoice.html");
        var layetext=document.getElementById(layer);
        generator.document.write(layetext.innerHTML.replace("Print Me"));
        generator.document.close();
        generator.print();
        generator.close();
    }
</script>
<div id="sales">
<?= GridView::widget([
        'dataProvider' => $RetaildataProvider,
        //'showFooter' => true, // show footer section of the gridview widget
        //'footerRowOptions'=>['style'=>'font-weight:bold;text-decoration: underline;'],
        'showPageSummary' => true,
        //'filterModel' => $searchModel2,
       // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label'=>'Spare part',
                'attribute'=>'spare_part',
                'pageSummary'=>'ToTal',
            ],
            //'customer',
            'quantity',
            'price',
            'discount',

            [
                'label' =>'Amount',
                'class' => '\kartik\grid\FormulaColumn',
                'value' => function ($model, $key, $index, $widget) {
                    $p = compact('model', 'key', 'index');
                    // Write your formula below
                    if($widget->col(4, $p) != 0){
                       $dis= ($widget->col(2, $p) * $widget->col(3, $p) * $widget->col(4, $p))/100;
                       return  ($widget->col(2, $p) * $widget->col(3, $p)) - $dis;
                    }
                    else{
                        return $widget->col(2, $p) * $widget->col(3, $p);
                    }
                    
                },
                'pageSummary'=>true,
            ],
            // [
            //     'class' => ActionColumn::className(),
            //     'template' => '{delete}',
            //     'urlCreator' => function ($action, app\models\RetailsInfo $model, $key, $index, $column) {
            //         return Url::toRoute([$action, 'id' => $model->id]);
            //      }
            // ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{vprint}',
                'buttons' => [
                    'vprint' => function ($url, $model, $key) {
                        return Html::a('<i class="glyphicon glyphicon-trash" style="font-size:px;color:red"></i>',['retails-info/delete','id'=>$model->id]
                        ,
                        [
                            //'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                            'method' => 'post',
                            ],
                        ]);
                    },

                ],
            
            ],
            
        ],
       
    ]);
    ?></div>
<!-- <a href="url/test.pdf" class="btn-pdfprint">open</a>
<input type="button"
        
         value="Go Somewhere Else"
         onclick="location.href='<%: Url.Action("Action", "Controller") %>'" /> -->

  <?= Html::a('Print', ['/retails/invoice','retails_id'=>$_REQUEST['retails_id']], ['class'=>'btn btn-primary']) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            [
                'label'=>'Spare Part',
                'attribute'=>'reference',
            ],
            //'customer',
            'quantity',
            'price',
            //'discount',
            //'created_at',
            //'created_by',
            //'updated_at',
            //'updated_by',
            [
                'class' => 'yii\grid\ActionColumn',
                // Html::button(Yii::t('app', ' Add Spare parts'), ['value'=>Url::to(['/order-details/create','order_id' => $model->order_id]),'class' => 'btn btn-success pull-right','id'=>'modalButton'])
                'template' => '{vprint}',
                    
                'buttons' => [
                    

                     'vprint' => function ($url, app\models\SpareParts $model, $key) {

    
                        return Html::a('<button class="btn btn-success pull-right" id="modalButton"><i>Sell</i></button>',['/retails-info/create','spare_part'=>$model->reference,'retails_id'=>$_REQUEST['retails_id']]
                        ,
                    );
                        
                        
                    },
    
                ],
            ],
        ],
    ]); ?>

<?= Html::a(Yii::t('app', 'Retails'), ['index'], ['class' => 'btn btn-success']) ?>


</div>

views/retails/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use kartik\grid\GridView;
/* @var $this yii\web\View */
/* @var $model app\models\Retails */

$this->title = $model->retails_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Retails'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="retails-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'retails_id' => $model->retails_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'retails_id' => $model->retails_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Print', ['/retails/invoice','retails_id'=>$_REQUEST['retails_id']], ['class'=>'btn btn-success']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'retails_id',
            'description',
            'created_at',
            'created_by',
            'updated_at',
            'updated_by',
            'customer',
        ],
    ]) ?>

<?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'showFooter' => true, // show footer section of the gridview widget
        //'footerRowOptions'=>['style'=>'font-weight:bold;text-decoration: underline;'],
        'showPageSummary' => true,
        //'filterModel' => $searchModel2,
       // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            //'id',
            [
                'label'=>'Spare part',
                'attribute'=>'spare_part',
                'pageSummary'=>'ToTal',
            ],
            //'customer',
            'quantity',
            'price',
            'discount',

            [
                'label' =>'Amount',
                'class' => '\kartik\grid\FormulaColumn',
                'value' => function ($model, $key, $index, $widget) {
                    $p = compact('model', 'key', 'index');
                    // Write your formula below
                    if($widget->col(4, $p) != 0){
                       $dis= ($widget->col(2, $p) * $widget->col(3, $p) * $widget->col(4, $p))/100;
                       return  ($widget->col(2, $p) * $widget->col(3, $p)) - $dis;
                    }
                    else{
                        return $widget->col(2, $p) * $widget->col(3, $p);
                    }
                    
                },
                'pageSummary'=>true,
            ],
           


            // [
            //     'class' => 'yii\grid\ActionColumn',
            //     'template' => '{vprint}',
            //     'buttons' => [
            //         'vprint' => function ($url, $model, $key) {
            //             return Html::a('<i class="glyphicon glyphicon-trash" style="font-size:px;color:red"></i>',['retails-info/delete','id'=>$model->id]
            //             ,
            //             [
            //                 //'class' => 'btn btn-danger',
            //                 'data' => [
            //                     'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            //                 'method' => 'post',
            //                 ],
            //             ]);
            //         },

            //     ],
            
            // ],
    ], 
    ]);
?>
   
    
    
    

</div>